apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2026.5.4 # check https://version.goauthentik.io for latest
    helm:
      valuesObject:
        authentik:
          secret_key: "" # overridden by global.env below

        postgresql:
          enabled: true
          image:
            tag: "18"
          auth:
            username: authentik
            database: authentik
            existingSecret: authentik-secret
            secretKeys:
              adminPasswordKey: AUTHENTIK_POSTGRESQL__PASSWORD
              userPasswordKey: AUTHENTIK_POSTGRESQL__PASSWORD

        server:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - auth.webernet.me

        global:
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-secret
                  key: AUTHENTIK_SECRET_KEY
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-secret
                  key: AUTHENTIK_POSTGRESQL__PASSWORD

  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
