apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobooks
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-audiobooks
  resources:
    requests:
      storage: 1500Gi
