apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebooks
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-ebooks
  resources:
    requests:
      storage: 100Gi
